name: Aux
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - requested

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-20.04

    steps:
    - name: Step 1
      run: |
        echo $GITHUB_REPOSITORY
        echo ${{ github.repository }}
