name: Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  base_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
  app: Accept:application/vnd.github.v3+json

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-20.04
    outputs:
      param1: ${{ steps.current.outputs.flag }}

    steps:
    - uses: actions/checkout@v2

    - name: First step
      id: current
      run: echo "::set-output name=flag::yes"


  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-20.04
    if: needs.job1.outputs.param1 == 'yes'
    outputs:
      started: ${{ steps.next.outputs.flag }}

    steps:
    - uses: actions/checkout@v2

    - name: First step
      id: next
      run: |
        echo "Hello" > test_file
        echo "::set-output name=flag::yes"
        exit 1

    - uses: actions/upload-artifact@v2
      with:
        name: memory_stat
        path: test_file

  job3:
    name: Job 3
    needs: job2
    runs-on: ubuntu-20.04
    if: needs.job2.outputs.started == 'yes'

    steps:
    - uses: actions/checkout@v2

    - name: First step
      run: echo "Reporting from Job 3!"
