name: Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  base_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
  app: Accept:application/vnd.github.v3+json

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: First step
      run: |
        pwd
        ls -l
        cd ~
        pwd
        ls -l

        eval url=$base_url/${{ github.run_id }}/jobs
        echo "url is $url"
        echo "app is $app"
        FOO=bar
        echo $FOO
        echo -e "Hello\nWorld\nI am here" | wc -l
        echo -e "Hello\nWorld\nI am here" | \
          wc -l
        echo -e "Hello\nWorld\nI am here" \
          | wc -l

    - name: Second step
      run: |
        eval url=$base_url/${{ github.run_id }}/jobs
        echo "url is $url"
        echo "app is $app"
        echo $FOO
        

  job2:
    name: Job 2
    runs-on: ubuntu-20.04

    steps:
    - name: First step
      run: |
        eval url=$base_url/${{ github.run_id }}/jobs
        echo "url is $url"
        echo "app is $app"
        echo $FOO
