name: Tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  base_url: $GITHUB_API_URL/repos/${{ github.repository }}/actions/run

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: First step
      run: echo $base_url

    - name: Second step
      run: |
        echo $base_url
        echo $GITHUB_REPOSITORY
        echo ${{ github.repository }}
        

  job2:
    name: Job 2
    runs-on: ubuntu-20.04

    steps:
    - name: First step
      run: echo $base_url
